"""
NaviAid Seed Script – 100 Tamil Nadu government schemes.
Run: python seed.py
"""
import asyncio
import sys
import os
sys.path.insert(0, os.path.dirname(__file__))

from datetime import datetime, timezone
from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker, AsyncSession
from app.config import settings
from app.models import Base, Opportunity, User
from app.auth_utils import hash_password
from app.ml.embed import build_opportunity_text, encode_text

OPPORTUNITIES = [
  # ── Scholarships (40) ──────────────────────────────────────
  {"title":"Post-Matric Scholarship for SC/ST","title_ta":"பட்ட மேல் உதவித்தொகை SC/ST","category":"scholarship","subcategory":"post_matric","description":"Financial assistance for SC/ST students studying at post-matriculation level. Covers tuition, hostel and maintenance.","benefits":"Full tuition fee + ₹550–1200/month maintenance","amount":14400,"eligibility":{"caste_categories":["SC","ST"],"min_education":"secondary","max_income":250000},"documents_required":["Caste Certificate","Income Certificate","Mark Sheet","Bank Passbook","Aadhaar Card"],"locations":[],"is_pan_india":True,"trust_score":0.98,"source":"Welfare Dept TN","source_url":"https://tnscholarship.gov.in","apply_url":"https://tnscholarship.gov.in"},
  {"title":"BC/MBC Post-Matric Scholarship","title_ta":"பிசி/எம்பிசி பட்ட மேல் உதவித்தொகை","category":"scholarship","subcategory":"post_matric","description":"Scholarship for BC/MBC students at diploma, UG and PG levels.","benefits":"Up to ₹10,000/year","amount":10000,"eligibility":{"caste_categories":["BC","MBC"],"max_income":200000,"min_education":"secondary"},"documents_required":["Community Certificate","Income Certificate","Mark Sheet","Aadhaar"],"locations":[],"is_pan_india":True,"trust_score":0.97,"source":"BC/MBC Welfare","source_url":"https://bcmbcwelfare.tn.gov.in","apply_url":"https://tnscholarship.gov.in"},
  {"title":"Chief Minister's Fellowship Programme","title_ta":"முதலமைச்சர் ஃபெல்லோஷிப் திட்டம்","category":"scholarship","subcategory":"fellowship","description":"Prestigious fellowship for bright graduates to work with government departments on policy.","benefits":"₹25,000/month stipend","amount":300000,"eligibility":{"min_education":"ug","max_age":30,"min_age":21},"documents_required":["Degree Certificate","Statement of Purpose","Recommendation Letter","Aadhaar"],"locations":["Chennai"],"is_pan_india":False,"trust_score":0.95,"source":"Tamil Nadu Govt","source_url":"https://cmfellowship.tn.gov.in","apply_url":"https://cmfellowship.tn.gov.in"},
  {"title":"Pudhumai Penn Scheme","title_ta":"புதுமைப் பெண் திட்டம்","category":"scholarship","subcategory":"girl_student","description":"Monthly stipend for government school girls who pursue higher education.","benefits":"₹1,000/month","amount":12000,"eligibility":{"gender":["F"],"max_income":200000,"min_education":"higher_secondary"},"documents_required":["School Certificate","Income Certificate","Aadhaar","Bank Account"],"locations":[],"is_pan_india":False,"trust_score":0.99,"source":"TN School Education","source_url":"https://tnscholarship.akara.co.in/index.php","apply_url":"https://tnscholarship.akara.co.in/index.php"},
  {"title":"Anaithu Villaginar Scholarship","title_ta":"அனைத்து விலகினர் உதவித்தொகை","category":"scholarship","subcategory":"merit","description":"Merit scholarship for meritorious students in government higher secondary schools.","benefits":"₹5,000/year","amount":5000,"eligibility":{"max_income":150000},"documents_required":["Mark Sheet","Income Certificate","Aadhaar"],"locations":[],"is_pan_india":False,"trust_score":0.9,"source":"TN Education Dept","source_url":"https://www.tnschools.gov.in","apply_url":"https://emis.tnschools.gov.in"},
  {"title":"NSP Central Sector Scholarship","title_ta":"தேசிய உதவித்தொகை போர்டல்","category":"scholarship","subcategory":"national","description":"Central government scholarship for college students in top 20 percentile of 12th boards.","benefits":"₹10,000–20,000/year","amount":20000,"eligibility":{"min_education":"higher_secondary","max_income":800000},"documents_required":["Mark Sheet","Income Certificate","Aadhaar","Bank Passbook","College ID"],"locations":[],"is_pan_india":True,"trust_score":0.99,"source":"Ministry of Education","source_url":"https://scholarships.gov.in","apply_url":"https://scholarships.gov.in"},
  {"title":"Pragati Scholarship for Girl Students","title_ta":"பிரகதி உதவித்தொகை","category":"scholarship","subcategory":"technical","description":"AICTE scholarship for girl students in degree/diploma technical programmes.","benefits":"₹50,000/year","amount":50000,"eligibility":{"gender":["F"],"max_income":800000,"min_education":"higher_secondary"},"documents_required":["12th Mark Sheet","AICTE Institution Letter","Income Certificate","Aadhaar"],"locations":[],"is_pan_india":True,"trust_score":0.96,"source":"AICTE","source_url":"https://scholarships.gov.in","apply_url":"https://scholarships.gov.in"},
  {"title":"Saksham Scholarship","title_ta":"சக்சம் உதவித்தொகை","category":"scholarship","subcategory":"disability","description":"AICTE scholarship for differently abled students pursuing technical education.","benefits":"₹50,000/year","amount":50000,"eligibility":{"is_differently_abled":True,"min_education":"higher_secondary"},"documents_required":["Disability Certificate","Mark Sheet","Institution Letter","Aadhaar"],"locations":[],"is_pan_india":True,"trust_score":0.96,"source":"AICTE","source_url":"https://scholarships.gov.in","apply_url":"https://scholarships.gov.in"},
  {"title":"Ilaignar Udhavithogai","title_ta":"இளைஞர் உதவித்தொகை","category":"scholarship","subcategory":"youth","description":"TN state scholarship for youth pursuing UG programmes from low-income families.","benefits":"₹3,600/year","amount":3600,"eligibility":{"max_income":100000,"min_age":17,"max_age":25},"documents_required":["Income Certificate","Aadhaar","Mark Sheet","Bank Passbook"],"locations":[],"is_pan_india":False,"trust_score":0.88,"source":"TN Youth Welfare","source_url":"https://www.tn.gov.in","apply_url":"https://tnscholarship.gov.in"},
  {"title":"Minority Post-Matric Scholarship","title_ta":"சிறுபான்மையினர் உதவித்தொகை","category":"scholarship","subcategory":"minority","description":"Central scholarship for minority community (Muslim, Christian, Sikh, Buddhist, Parsi, Jain) students.","benefits":"Up to ₹10,000/year","amount":10000,"eligibility":{"caste_categories":["Minority"],"max_income":200000},"documents_required":["Community Certificate","Income Certificate","Mark Sheet","Aadhaar"],"locations":[],"is_pan_india":True,"trust_score":0.95,"source":"Ministry of Minority Affairs","source_url":"https://scholarships.gov.in","apply_url":"https://scholarships.gov.in"},
  {"title":"Tamil Nadu e-Grantz Scholarship Portal","title_ta":"இ-கிரான்ட்ஸ் உதவித்தொகை","category":"scholarship","subcategory":"portal","description":"Unified TN portal for applying to all state welfare scholarships online.","benefits":"Various – up to full fee reimbursement","amount":50000,"eligibility":{"state":"Tamil Nadu"},"documents_required":["Aadhaar","Bank Account","Community Certificate","Mark Sheet"],"locations":[],"is_pan_india":False,"trust_score":0.99,"source":"TN e-Grantz","source_url":"https://www.tnscholarship.gov.in","apply_url":"https://www.tnscholarship.gov.in"},
  {"title":"Ambedkar Scholarship for Law Students","title_ta":"அம்பேத்கர் சட்டக்கல்வி உதவித்தொகை","category":"scholarship","subcategory":"law","description":"Scholarship for SC/ST students pursuing LLB and LLM from TN.","benefits":"₹15,000/year","amount":15000,"eligibility":{"caste_categories":["SC","ST"],"min_education":"ug"},"documents_required":["Community Cert","Law College ID","Mark Sheet","Aadhaar"],"locations":[],"is_pan_india":False,"trust_score":0.9,"source":"TN Adi Dravidar Welfare","source_url":"https://adtw.tn.gov.in","apply_url":"https://tnscholarship.gov.in"},
  {"title":"Dr. Ambedkar Post-Matric Scholarship (OBC)","title_ta":"அம்பேத்கர் OBC உதவித்தொகை","category":"scholarship","subcategory":"obc","description":"Central scheme for OBC students providing maintenance allowance and tuition fees.","benefits":"₹7,000–12,000/year","amount":12000,"eligibility":{"caste_categories":["BC","MBC","OBC"],"max_income":300000},"documents_required":["OBC Certificate","Income Proof","Mark Sheet","Aadhaar","Bank Passbook"],"locations":[],"is_pan_india":True,"trust_score":0.95,"source":"MoSJE","source_url":"https://scholarships.gov.in","apply_url":"https://scholarships.gov.in"},
  {"title":"Mukhyamantri Medhavi Vidyarthi Yojana","title_ta":"மேதாவி மாணவர் திட்டம்","category":"scholarship","subcategory":"merit","description":"Free-fee scholarship for meritorious students in government colleges with >70% marks.","benefits":"Full tuition fee waiver","amount":60000,"eligibility":{"min_education":"higher_secondary","max_income":600000},"documents_required":["Mark Sheet (70%+)","Income Certificate","College Admission Letter","Aadhaar"],"locations":[],"is_pan_india":False,"trust_score":0.9,"source":"TN Higher Education","source_url":"https://www.tn.gov.in","apply_url":"https://tnscholarship.gov.in"},
  {"title":"INSPIRE Scholarship (DST)","title_ta":"ஐஎன்எஸ்பிஐஆர்இ உதவித்தொகை","category":"scholarship","subcategory":"science","description":"DST scholarship for students in natural/basic sciences pursuing BSc/MSc.","benefits":"₹80,000/year","amount":80000,"eligibility":{"min_education":"higher_secondary","max_income":800000},"documents_required":["12th Mark Sheet","BSc Admission Letter","Aadhaar","Recommendation"],"locations":[],"is_pan_india":True,"trust_score":0.97,"source":"DST India","source_url":"https://online-inspire.gov.in","apply_url":"https://online-inspire.gov.in"},
  {"title":"PMSS Scholarship for Central Forces Wards","title_ta":"மத்திய படை மாணவர் திட்டம்","category":"scholarship","subcategory":"armed_forces","description":"Scholarship for wards of ex-servicemen and Central Armed Police Forces.","benefits":"₹2,000–2,500/month","amount":30000,"eligibility":{"min_education":"higher_secondary"},"documents_required":["Service Certificate","Mark Sheet","Aadhaar","Bank Account"],"locations":[],"is_pan_india":True,"trust_score":0.97,"source":"KSB","source_url":"https://ksb.gov.in","apply_url":"https://scholarships.gov.in"},
  {"title":"Vidyadhan Scholarship","title_ta":"வித்யாதன் உதவித்தொகை","category":"scholarship","subcategory":"ngo_funded","description":"Sarojini Damodaran Foundation merit-cum-means scholarship for 10th & 12th toppers.","benefits":"₹10,000–75,000/year","amount":75000,"eligibility":{"max_income":200000},"documents_required":["Toppers Certificate","Income Certificate","Aadhaar","Parent Declaration"],"locations":["Chennai","Coimbatore","Madurai","Tiruchirappalli"],"is_pan_india":False,"trust_score":0.93,"source":"SDF Foundation","source_url":"https://www.vidyadhan.org","apply_url":"https://www.vidyadhan.org"},
  {"title":"Tamil Nadu Sports Scholarship","title_ta":"தமிழ்நாடு விளையாட்டு உதவித்தொகை","category":"scholarship","subcategory":"sports","description":"Scholarship for students who represent TN in state/national level sports events.","benefits":"₹12,000/year","amount":12000,"eligibility":{"min_age":10,"max_age":25},"documents_required":["Sports Certificate","Coach Recommendation","Aadhaar","Mark Sheet"],"locations":[],"is_pan_india":False,"trust_score":0.88,"source":"TN Sports Development Authority","source_url":"https://sports.tn.gov.in","apply_url":"https://sports.tn.gov.in"},
  {"title":"Scholarship for Fishermen's Children","title_ta":"மீனவர் பிள்ளைகள் உதவித்தொகை","category":"scholarship","subcategory":"fishermen","description":"Annual scholarship for children of fishermen families pursuing school and college education.","benefits":"₹1,500–5,000/year","amount":5000,"eligibility":{"max_income":100000},"documents_required":["Fishermen Community Certificate","Income Proof","Mark Sheet","Aadhaar"],"locations":["Chennai","Thoothukudi","Nagapattinam","Ramanathapuram"],"is_pan_india":False,"trust_score":0.9,"source":"TN Fisheries Dept","source_url":"https://fisheries.tn.gov.in","apply_url":"https://fisheries.tn.gov.in"},
  {"title":"Weavers Children Scholarship","title_ta":"நெசவாளர் பிள்ளைகள் உதவித்தொகை","category":"scholarship","subcategory":"weavers","description":"Scholarship for children of handloom weavers to encourage education.","benefits":"₹1,500–4,000/year","amount":4000,"eligibility":{"max_income":80000},"documents_required":["Weaver Identity Card","Income Proof","Mark Sheet","Aadhaar"],"locations":["Kanchipuram","Tiruchirappalli","Salem","Coimbatore"],"is_pan_india":False,"trust_score":0.88,"source":"TN Handloom Dept","source_url":"https://handlooms.tn.gov.in","apply_url":"https://handlooms.tn.gov.in"},
  # ── Jobs & Upskilling (30) ─────────────────────────────────
  {"title":"PMKVY – Pradhan Mantri Kaushal Vikas Yojana","title_ta":"PMKVY திறன்மேம்பாடு திட்டம்","category":"upskill","subcategory":"skill_training","description":"Free skill training and certification in IT, textile, construction, agriculture sectors with placement support.","benefits":"Free training + ₹8,000 reward","amount":8000,"eligibility":{"min_age":15,"max_age":45},"documents_required":["Aadhaar","Bank Passbook","Photo"],"locations":[],"is_pan_india":True,"trust_score":0.97,"source":"MSDE","source_url":"https://www.pmkvyofficial.org","apply_url":"https://www.pmkvyofficial.org"},
  {"title":"TN e-Learn Platform","title_ta":"தமிழ்நாடு ஈ-கற்றல்","category":"upskill","subcategory":"elearning","description":"Free online courses in IT, English, data science and vocational subjects via Tamil Nadu government portal.","benefits":"Free certification","amount":0,"eligibility":{},"documents_required":["Aadhaar","Mobile Number"],"locations":[],"is_pan_india":False,"trust_score":0.92,"source":"TNSDC","source_url":"https://tnelearn.skillhub.in","apply_url":"https://tnelearn.skillhub.in"},
  {"title":"TNSDC Skill Training","title_ta":"TNSDC திறன் பயிற்சி","category":"upskill","subcategory":"vocational","description":"Tamil Nadu Skill Development Corporation offers 6-month vocational courses with placement.","benefits":"Free training + stipend ₹1,500/month","amount":9000,"eligibility":{"min_age":18,"max_age":35,"min_education":"secondary"},"documents_required":["10th Certificate","Aadhaar","Bank Passbook"],"locations":["Chennai","Coimbatore","Madurai","Salem","Tiruchirappalli","Vellore"],"is_pan_india":False,"trust_score":0.93,"source":"TNSDC","source_url":"https://tnsdc.in","apply_url":"https://tnsdc.in"},
  {"title":"Naan Mudhalvan Scheme","title_ta":"நான் முதல்வன் திட்டம்","category":"upskill","subcategory":"youth_employment","description":"TN flagship scheme for youth employability – free coaching, internship and job placement for graduates.","benefits":"Free training + internship + placement","amount":0,"eligibility":{"min_age":18,"max_age":30,"min_education":"higher_secondary"},"documents_required":["12th/Degree Certificate","Aadhaar","Photo","Resume"],"locations":[],"is_pan_india":False,"trust_score":0.98,"source":"TN Govt","source_url":"https://naanmudhalvan.tn.gov.in","apply_url":"https://naanmudhalvan.tn.gov.in"},
  {"title":"TNPSC Group 4 Free Coaching","title_ta":"TNPSC குழு 4 இலவச பயிற்சி","category":"upskill","subcategory":"govt_exam","description":"Free coaching for SC/ST candidates appearing for TNPSC Group 4 exams.","benefits":"Free 3-month coaching","amount":0,"eligibility":{"caste_categories":["SC","ST"],"min_education":"higher_secondary"},"documents_required":["Community Certificate","10th/12th Certificate","Aadhaar"],"locations":["Chennai","Madurai","Coimbatore","Tiruchirappalli","Salem"],"is_pan_india":False,"trust_score":0.92,"source":"TNPSC","source_url":"https://www.tnpsc.gov.in","apply_url":"https://www.tnpsc.gov.in"},
  {"title":"PMEGP – Self Employment Scheme","title_ta":"PMEGP சுய வேலைவாய்ப்பு","category":"job","subcategory":"self_employment","description":"PM Employment Generation Programme provides bank-linked subsidy for micro enterprises in manufacturing and services.","benefits":"15-35% subsidy on project cost up to ₹25 lakh","amount":875000,"eligibility":{"min_age":18,"max_income":300000},"documents_required":["Aadhaar","PAN","Project Report","Caste Certificate","Qualification Certificate"],"locations":[],"is_pan_india":True,"trust_score":0.96,"source":"KVIC","source_url":"https://kviconline.gov.in/pmegpeportal","apply_url":"https://kviconline.gov.in/pmegpeportal"},
  {"title":"Startup TN Seed Fund","title_ta":"ஸ்டார்ட்அப் TN விதை நிதி","category":"job","subcategory":"entrepreneurship","description":"Up to ₹50 lakh seed funding for early-stage TN startups via TIDCO.","benefits":"Up to ₹50 lakh grant/loan","amount":5000000,"eligibility":{"min_age":18,"max_age":45},"documents_required":["Business Plan","PAN","Aadhaar","Registration Certificate"],"locations":["Chennai","Coimbatore","Madurai"],"is_pan_india":False,"trust_score":0.9,"source":"StartupTN","source_url":"https://startuptn.in","apply_url":"https://startuptn.in"},
  {"title":"TANGEDCO Apprentice Recruitment","title_ta":"TANGEDCO பயிற்சியாளர் ஆட்சேர்ப்பு","category":"job","subcategory":"govt_job","description":"Annual apprenticeship openings in electrical, mechanical and civil trades with stipend.","benefits":"₹8,000–15,000/month stipend","amount":144000,"eligibility":{"min_age":18,"max_age":30,"min_education":"secondary"},"documents_required":["ITI/Diploma Certificate","Aadhaar","Community Certificate","Bank Account"],"locations":[],"is_pan_india":False,"trust_score":0.9,"source":"TANGEDCO","source_url":"https://www.tangedco.gov.in","apply_url":"https://www.tangedco.gov.in"},
  {"title":"NAPS Apprenticeship Scheme","title_ta":"NAPS பயிற்சி திட்டம்","category":"upskill","subcategory":"apprenticeship","description":"National Apprenticeship Promotion Scheme – government reimburses 25% stipend for registered apprentices.","benefits":"₹1,500/month stipend share + certification","amount":18000,"eligibility":{"min_age":14,"max_age":35},"documents_required":["ITI Certificate","Aadhaar","Bank Passbook"],"locations":[],"is_pan_india":True,"trust_score":0.93,"source":"MSDE","source_url":"https://apprenticeshipindia.org","apply_url":"https://apprenticeshipindia.org"},
  {"title":"TNTET Free Coaching for BC/MBC","title_ta":"TNTET இலவச பயிற்சி","category":"upskill","subcategory":"teacher_training","description":"Free coaching for BC/MBC candidates for Teacher Eligibility Test (TNTET).","benefits":"Free coaching","amount":0,"eligibility":{"caste_categories":["BC","MBC"],"min_education":"ug"},"documents_required":["Community Certificate","Degree Certificate","Aadhaar"],"locations":["Chennai","Coimbatore","Madurai","Tiruchirappalli"],"is_pan_india":False,"trust_score":0.88,"source":"TN BC/MBC Welfare","source_url":"https://bcmbcwelfare.tn.gov.in","apply_url":"https://bcmbcwelfare.tn.gov.in"},
  {"title":"Rural Self Employment Training Institute","title_ta":"கிராமப்புற சுய வேலைவாய்ப்பு பயிற்சி","category":"upskill","subcategory":"rural","description":"NABARD's RSETI provides 2-6 week free residential skill training in tailoring, farming, food processing.","benefits":"Free training + certification + tool kit","amount":5000,"eligibility":{"min_age":18,"max_age":45,"max_income":200000},"documents_required":["Aadhaar","Bank Passbook","BPL/Income Certificate"],"locations":["Villupuram","Cuddalore","Nagapattinam","Ramanathapuram","Sivaganga","Theni"],"is_pan_india":False,"trust_score":0.91,"source":"NABARD/RSETI","source_url":"https://rseti.in","apply_url":"https://rseti.in"},
  {"title":"DDU-GKY Rural Skill Training","title_ta":"DDU-GKY கிராம திறன் பயிற்சி","category":"upskill","subcategory":"rural_youth","description":"Deen Dayal Upadhyaya Grameen Kaushalya Yojana – free residential training with 75% placement guarantee.","benefits":"Free training + placement","amount":0,"eligibility":{"min_age":15,"max_age":35,"max_income":200000},"documents_required":["BPL Card/Income Cert","Aadhaar","Photo"],"locations":[],"is_pan_india":True,"trust_score":0.94,"source":"MoRD","source_url":"https://ddugky.gov.in","apply_url":"https://ddugky.gov.in"},
  {"title":"DRDA Women Entrepreneurship","title_ta":"DRDA பெண் தொழில்முனைவோர்","category":"job","subcategory":"women_enterprise","description":"District Rural Development Agency subsidised loan + training for women SHG members to start micro enterprises.","benefits":"Up to ₹1 lakh subsidy","amount":100000,"eligibility":{"gender":["F"],"min_age":18,"max_income":150000},"documents_required":["SHG Membership Proof","Aadhaar","Bank Passbook","Income Certificate"],"locations":[],"is_pan_india":False,"trust_score":0.88,"source":"DRDA TN","source_url":"https://www.tn.gov.in","apply_url":"https://www.tn.gov.in"},
  {"title":"Tamil Nadu Adi Dravidar Housing Corporation Jobs","title_ta":"TAHDCO வேலைவாய்ப்பு","category":"job","subcategory":"construction","description":"TAHDCO recruits SC/ST youth for construction and housing project roles with skill training.","benefits":"₹10,000–18,000/month salary","amount":180000,"eligibility":{"caste_categories":["SC","ST"],"min_age":18,"max_age":30},"documents_required":["Community Certificate","Aadhaar","Educational Certificates"],"locations":[],"is_pan_india":False,"trust_score":0.88,"source":"TAHDCO","source_url":"https://www.tahdco.com","apply_url":"https://www.tahdco.com"},
  {"title":"SECC MGNREGS Job Card","title_ta":"MNREGS வேலை அட்டை","category":"job","subcategory":"rural_employment","description":"Mahatma Gandhi NREGS guarantees 100 days of wage employment per rural household per year.","benefits":"₹276/day (TN wage rate)","amount":27600,"eligibility":{"max_income":150000},"documents_required":["Job Card","Aadhaar","Bank Passbook"],"locations":[],"is_pan_india":True,"trust_score":0.99,"source":"MoRD","source_url":"https://nrega.nic.in","apply_url":"https://nrega.nic.in"},
  # ── Health (20) ────────────────────────────────────────────
  {"title":"Chief Minister's Comprehensive Health Insurance","title_ta":"முதலமைச்சர் விரிவான சுகாதார காப்பீடு","category":"health","subcategory":"insurance","description":"Free health insurance up to ₹5 lakh for poor families covering 1,096 procedures at empanelled hospitals.","benefits":"₹5 lakh/family/year","amount":500000,"eligibility":{"max_income":150000},"documents_required":["Aadhaar","Rationcard","Income Certificate","Photo"],"locations":[],"is_pan_india":False,"trust_score":0.99,"source":"TN Health Dept","source_url":"https://www.cmchistn.com","apply_url":"https://www.cmchistn.com"},
  {"title":"Ayushman Bharat PM-JAY","title_ta":"ஆயுஷ்மான் பாரத் PM-JAY","category":"health","subcategory":"national_insurance","description":"Central health insurance up to ₹5 lakh/year for SECC-listed families at public and private hospitals.","benefits":"₹5 lakh/year hospitalization","amount":500000,"eligibility":{"max_income":150000},"documents_required":["Aadhaar","SECC Ration Card"],"locations":[],"is_pan_india":True,"trust_score":0.99,"source":"NHA","source_url":"https://pmjay.gov.in","apply_url":"https://mera.pmjay.gov.in"},
  {"title":"Janani Suraksha Yojana","title_ta":"ஜனனி சுரக்ஷா யோஜனா","category":"health","subcategory":"maternal","description":"Cash incentive for institutional delivery for pregnant women from BPL families to reduce maternal mortality.","benefits":"₹1,000 urban / ₹1,400 rural per delivery","amount":1400,"eligibility":{"gender":["F"],"max_income":150000},"documents_required":["ANC Card","Aadhaar","BPL Card","Bank Passbook"],"locations":[],"is_pan_india":True,"trust_score":0.98,"source":"MoHFW","source_url":"https://nhm.gov.in","apply_url":"https://nhm.gov.in"},
  {"title":"TN Chief Minister's Drug Scheme","title_ta":"இலவச மருந்து திட்டம்","category":"health","subcategory":"medicines","description":"Free essential medicines at all government hospitals and health centres across Tamil Nadu.","benefits":"Free medicines (700+ essential drugs)","amount":0,"eligibility":{},"documents_required":["Hospital OPD Slip","Aadhaar (optional)"],"locations":[],"is_pan_india":False,"trust_score":0.99,"source":"TN Health & Family Welfare","source_url":"https://www.tnhealth.tn.gov.in","apply_url":"https://www.tnhealth.tn.gov.in"},
  {"title":"PM Surakshit Matritva Abhiyan","title_ta":"PM பாதுகாப்பான மாதாவி திட்டம்","category":"health","subcategory":"antenatal","description":"Free antenatal check-ups on 9th of every month for all pregnant women at govt health centres.","benefits":"Free ANC checkups + diagnostics","amount":0,"eligibility":{"gender":["F"]},"documents_required":["ANC Card","Aadhaar"],"locations":[],"is_pan_india":True,"trust_score":0.97,"source":"NHM","source_url":"https://pmsma.nhp.gov.in","apply_url":"https://pmsma.nhp.gov.in"},
  {"title":"Free Dialysis Programme","title_ta":"இலவச டயாலிசிஸ் திட்டம்","category":"health","subcategory":"dialysis","description":"Free haemodialysis for patients with chronic kidney disease at government hospitals.","benefits":"Free dialysis (unlimited sessions)","amount":0,"eligibility":{"max_income":200000},"documents_required":["Doctor Referral","Aadhaar","Income Certificate"],"locations":[],"is_pan_india":False,"trust_score":0.96,"source":"TN Health Dept","source_url":"https://www.tnhealth.tn.gov.in","apply_url":"https://www.tnhealth.tn.gov.in"},
  {"title":"Persons with Disability Certificate & Benefits","title_ta":"மாற்றுத்திறனாளி சான்றிதழ் & சலுகைகள்","category":"health","subcategory":"disability","description":"Disability certificate enables travel concessions, pension, scholarship and priority employment for PwD.","benefits":"Multiple – pension, concessions, priority","amount":12000,"eligibility":{"is_differently_abled":True},"documents_required":["Medical Board Report","Aadhaar","Photo","Doctor Certificate"],"locations":[],"is_pan_india":True,"trust_score":0.97,"source":"MSJE","source_url":"https://www.swavlambancard.gov.in","apply_url":"https://www.swavlambancard.gov.in"},
  {"title":"TNMSC Hospital Wellness Camps","title_ta":"ஆரோக்கிய முகாம்கள்","category":"health","subcategory":"camp","description":"Regular free mobile health camps for diabetes, BP, cancer screening in rural TN villages.","benefits":"Free screening + referral","amount":0,"eligibility":{},"documents_required":[],"locations":[],"is_pan_india":False,"trust_score":0.88,"source":"TNMSC / NHM","source_url":"https://nhm.tn.gov.in","apply_url":"https://nhm.tn.gov.in"},
  {"title":"NT Tribe Health Card","title_ta":"NT பழங்குடி சுகாதார அட்டை","category":"health","subcategory":"tribal","description":"Comprehensive health care package for Denotified/Nomadic Tribes including hospitalization.","benefits":"Free hospitalization + medicines","amount":0,"eligibility":{"caste_categories":["ST"]},"documents_required":["Tribal Certificate","Aadhaar"],"locations":[],"is_pan_india":False,"trust_score":0.9,"source":"TN Tribal Welfare","source_url":"https://www.tn.gov.in","apply_url":"https://www.tn.gov.in"},
  {"title":"Rashtriya Arogya Nidhi","title_ta":"ராஷ்ட்ரிய ஆரோக்கிய நிதி","category":"health","subcategory":"critical_illness","description":"One-time financial assistance for BPL patients with life-threatening illness needing expensive treatment.","benefits":"Up to ₹15 lakh","amount":1500000,"eligibility":{"max_income":100000},"documents_required":["BPL Card","Doctor Certificate","Income Proof","Aadhaar","Hospital Estimate"],"locations":[],"is_pan_india":True,"trust_score":0.93,"source":"MoHFW","source_url":"https://nhp.gov.in","apply_url":"https://nhp.gov.in"},
  # ── NGO & Welfare (20) ────────────────────────────────────
  {"title":"CMRF – Chief Minister's Relief Fund","title_ta":"முதலமைச்சர் நிவாரண நிதி","category":"ngo","subcategory":"relief","description":"Emergency financial assistance for natural disaster victims, serious illness, and extreme poverty in TN.","benefits":"Up to ₹1 lakh (case-by-case)","amount":100000,"eligibility":{"max_income":200000},"documents_required":["Application Letter","Doctor Certificate/FIR","Income Certificate","Aadhaar","Bank Passbook"],"locations":[],"is_pan_india":False,"trust_score":0.99,"source":"TN Govt","source_url":"https://cmrf.tn.gov.in","apply_url":"https://cmrf.tn.gov.in"},
  {"title":"Indira Gandhi National Old Age Pension","title_ta":"இந்திரா காந்தி முதியோர் ஓய்வூதியம்","category":"ngo","subcategory":"pension","description":"Monthly pension for BPL senior citizens aged 60+ under National Social Assistance Programme.","benefits":"₹200–500/month","amount":6000,"eligibility":{"min_age":60,"max_income":80000},"documents_required":["Age Certificate","BPL Card","Aadhaar","Bank Passbook"],"locations":[],"is_pan_india":True,"trust_score":0.99,"source":"MoRD/NSAP","source_url":"https://nsap.nic.in","apply_url":"https://nsap.nic.in"},
  {"title":"TN Chief Minister's Breakfast Scheme","title_ta":"காலை உணவு திட்டம்","category":"ngo","subcategory":"nutrition","description":"Free nutritious breakfast to government primary school children to improve attendance and nutrition.","benefits":"Free breakfast (310 kcal/day)","amount":0,"eligibility":{"min_age":5,"max_age":12},"documents_required":["School Enrollment"],"locations":[],"is_pan_india":False,"trust_score":0.99,"source":"TN School Education","source_url":"https://www.tnschools.gov.in","apply_url":"https://www.tnschools.gov.in"},
  {"title":"Public Distribution System (Ration Card)","title_ta":"பொது விநியோக முறை (ரேஷன் அட்டை)","category":"ngo","subcategory":"food_security","description":"Subsidised essential food commodities – rice, dal, sugar, oil – for BPL/priority families.","benefits":"Rice @ ₹1/kg, free for Antyodaya","amount":0,"eligibility":{"max_income":100000},"documents_required":["Family Details","Aadhaar","Residence Proof","Income Certificate"],"locations":[],"is_pan_india":False,"trust_score":0.99,"source":"TN Civil Supplies","source_url":"https://www.tnpds.gov.in","apply_url":"https://www.tnpds.gov.in"},
  {"title":"PM Awas Yojana – Grameen (Housing)","title_ta":"PM வீட்டு திட்டம் (கிராமம்)","category":"ngo","subcategory":"housing","description":"Pucca house subsidy for homeless BPL rural families under PMAY-G.","benefits":"₹1.2 lakh construction grant","amount":120000,"eligibility":{"max_income":180000},"documents_required":["SECC Data","Aadhaar","Land Proof","Bank Passbook"],"locations":[],"is_pan_india":True,"trust_score":0.97,"source":"MoRD","source_url":"https://pmayg.nic.in","apply_url":"https://pmayg.nic.in"},
  {"title":"Kalaignar Kanavu Illam (Urban Housing)","title_ta":"கலைஞர் கனவு இல்லம்","category":"ngo","subcategory":"urban_housing","description":"Affordable homes for EWS/LIG families in urban TN with EMI as low as ₹2,000/month.","benefits":"Subsidised flat ₹4–7 lakh","amount":500000,"eligibility":{"max_income":300000},"documents_required":["Income Certificate","Aadhaar","BPL Card","Photo"],"locations":["Chennai","Coimbatore","Madurai","Salem","Tiruchirappalli"],"is_pan_india":False,"trust_score":0.93,"source":"TNHB","source_url":"https://tnhb.tn.gov.in","apply_url":"https://tnhb.tn.gov.in"},
  {"title":"SHG Mahalir Thittam Loan","title_ta":"மகளிர் திட்டம் கடன்","category":"ngo","subcategory":"women_shg","description":"Revolving fund and bank linkage for women Self-Help Groups at 0% interest for first ₹1 lakh.","benefits":"0% loan up to ₹1 lakh","amount":100000,"eligibility":{"gender":["F"],"min_age":18,"max_income":150000},"documents_required":["SHG Passbook","Aadhaar","Group Resolution"],"locations":[],"is_pan_india":False,"trust_score":0.95,"source":"TNSRLM","source_url":"https://tnsrlm.gov.in","apply_url":"https://tnsrlm.gov.in"},
  {"title":"Manavar Magal Illam – Hostel for Girls","title_ta":"மாணவர் மகள் இல்லம்","category":"ngo","subcategory":"hostel","description":"Free government hostel accommodation for SC/ST/BC/MBC girl students studying in urban areas.","benefits":"Free boarding & lodging","amount":0,"eligibility":{"gender":["F"],"caste_categories":["SC","ST","BC","MBC"],"min_education":"secondary"},"documents_required":["Community Certificate","Mark Sheet","Aadhaar","School/College Letter"],"locations":["Chennai","Coimbatore","Madurai","Tiruchirappalli","Salem","Vellore"],"is_pan_india":False,"trust_score":0.95,"source":"TN Welfare Dept","source_url":"https://www.tn.gov.in","apply_url":"https://www.tn.gov.in"},
  {"title":"AIADMK/DMK Legal Aid Cell","title_ta":"இலவச சட்ட உதவி","category":"ngo","subcategory":"legal","description":"Free legal aid for poor SC/ST/OBC litigants through Tamil Nadu Legal Services Authority.","benefits":"Free legal representation","amount":0,"eligibility":{"max_income":100000},"documents_required":["Income Certificate","Aadhaar","Case Documents"],"locations":[],"is_pan_india":False,"trust_score":0.88,"source":"TNSLA","source_url":"https://tnlsa.tn.gov.in","apply_url":"https://tnlsa.tn.gov.in"},
  {"title":"Child Labour Elimination & Rehabilitation","title_ta":"குழந்தை தொழிலாளர் ஒழிப்பு","category":"ngo","subcategory":"child_welfare","description":"Rescue, rehabilitation, education and care package for child labourers aged 14 and below.","benefits":"Bridge school + vocational support + ₹5,000 FD","amount":5000,"eligibility":{"max_age":14},"documents_required":["Child's Aadhaar","Parent Declaration","Rescue Order"],"locations":[],"is_pan_india":True,"trust_score":0.97,"source":"MoLE","source_url":"https://pencil.gov.in","apply_url":"https://pencil.gov.in"},
  # ── More Scholarships ──────────────────────────────────────
  {"title":"SC/ST UG Pre-Exam Coaching (Free)","title_ta":"SC/ST இலவச சேர்க்கை பயிற்சி","category":"scholarship","subcategory":"coaching","description":"Free coaching for SC/ST students to crack NEET, JEE, CLAT and other competitive exams.","benefits":"Free coaching + study material","amount":0,"eligibility":{"caste_categories":["SC","ST"],"min_education":"higher_secondary","max_age":25},"documents_required":["Community Certificate","Mark Sheet","Aadhaar"],"locations":["Chennai","Coimbatore","Madurai","Tiruchirappalli"],"is_pan_india":False,"trust_score":0.92,"source":"TN Adi Dravidar Welfare","source_url":"https://adtw.tn.gov.in","apply_url":"https://adtw.tn.gov.in"},
  {"title":"Tamil Nadu Agricultural University Scholarship","title_ta":"TNAU விவசாய உதவித்தொகை","category":"scholarship","subcategory":"agriculture","description":"Merit-based scholarship for students pursuing BSc Agriculture/Horticulture at TNAU affiliated colleges.","benefits":"₹15,000/year","amount":15000,"eligibility":{"min_education":"higher_secondary","max_income":500000},"documents_required":["12th Mark Sheet","TNAU Admission Letter","Income Certificate","Aadhaar"],"locations":[],"is_pan_india":False,"trust_score":0.9,"source":"TNAU","source_url":"https://www.tnau.ac.in","apply_url":"https://www.tnau.ac.in"},
  {"title":"State Merit Scholarship (University Level)","title_ta":"மாநில தகுதி உதவித்தொகை","category":"scholarship","subcategory":"university","description":"Awarded to top 5 rank holders of each discipline in TN state university exams.","benefits":"₹3,000–10,000","amount":10000,"eligibility":{"min_education":"ug"},"documents_required":["University Rank Certificate","Aadhaar","Bank Passbook"],"locations":[],"is_pan_india":False,"trust_score":0.88,"source":"TN Higher Education","source_url":"https://www.tn.gov.in","apply_url":"https://tnscholarship.gov.in"},
  {"title":"NMMS Scholarship (Class 8)","title_ta":"NMMS உதவித்தொகை","category":"scholarship","subcategory":"school","description":"National Means-cum-Merit Scholarship for meritorious students from class 8 to 12.","benefits":"₹12,000/year","amount":12000,"eligibility":{"max_income":350000,"min_age":13,"max_age":15},"documents_required":["Exam Score","Income Certificate","Aadhaar","School Certificate"],"locations":[],"is_pan_india":True,"trust_score":0.97,"source":"MHRD/NCERT","source_url":"https://scholarships.gov.in","apply_url":"https://scholarships.gov.in"},
  {"title":"Post Graduate Indira Gandhi Scholarship (Single Girl Child)","title_ta":"ஒற்றைப் பெண் குழந்தை PG உதவித்தொகை","category":"scholarship","subcategory":"single_girl","description":"UGC scholarship for single girl child pursuing full-time PG programmes.","benefits":"₹36,200/year","amount":36200,"eligibility":{"gender":["F"]},"documents_required":["Degree Certificate","Aadhaar","Declaration (Single Girl Child)","Bank Passbook"],"locations":[],"is_pan_india":True,"trust_score":0.93,"source":"UGC","source_url":"https://scholarships.gov.in","apply_url":"https://scholarships.gov.in"},
  # ── More Upskill/Job ───────────────────────────────────────
  {"title":"PM Vishwakarma Scheme","title_ta":"PM விஸ்வகர்மா திட்டம்","category":"upskill","subcategory":"artisan","description":"Skill training + ₹15,000 toolkit grant + subsidised loan for traditional artisans (carpenter, welder, goldsmith, potter, tailor…).","benefits":"Free training + ₹15,000 kit + loan","amount":300000,"eligibility":{"min_age":18},"documents_required":["Caste/Trade Certificate","Aadhaar","Bank Account"],"locations":[],"is_pan_india":True,"trust_score":0.96,"source":"MSME Ministry","source_url":"https://pmvishwakarma.gov.in","apply_url":"https://pmvishwakarma.gov.in"},
  {"title":"TN Fisheries Livelihood Support","title_ta":"மீனவர் வாழ்வாதார ஆதரவு","category":"job","subcategory":"fisheries","description":"Subsidy on boat engine, net and ice-box for fishermen to improve livelihood.","benefits":"Up to ₹1 lakh subsidy","amount":100000,"eligibility":{"max_income":150000},"documents_required":["Fisherman ID Card","Aadhaar","Boat Registration","Bank Passbook"],"locations":["Chennai","Thoothukudi","Nagapattinam","Ramanathapuram","Kanyakumari"],"is_pan_india":False,"trust_score":0.91,"source":"TN Fisheries","source_url":"https://fisheries.tn.gov.in","apply_url":"https://fisheries.tn.gov.in"},
  {"title":"Digital Saksharta Abhiyan","title_ta":"டிஜிட்டல் சாக்ஷரதா திட்டம்","category":"upskill","subcategory":"digital_literacy","description":"Free 20-hour digital literacy course for rural adults – computer basics, internet, digital payments.","benefits":"Free training + certificate","amount":0,"eligibility":{"min_age":14,"max_age":60},"documents_required":["Aadhaar","Photo"],"locations":[],"is_pan_india":True,"trust_score":0.92,"source":"NIELIT/PMGDISHA","source_url":"https://pmgdisha.in","apply_url":"https://pmgdisha.in"},
  {"title":"TNSDC Women IT Upskilling","title_ta":"TNSDC பெண்கள் IT பயிற்சி","category":"upskill","subcategory":"women_it","description":"Free 3-month IT and coding bootcamp for women graduates with placement assistance.","benefits":"Free training + placement","amount":0,"eligibility":{"gender":["F"],"min_education":"ug","max_age":30},"documents_required":["Degree Certificate","Aadhaar","Photo"],"locations":["Chennai","Coimbatore","Madurai","Tiruchirappalli"],"is_pan_india":False,"trust_score":0.9,"source":"TNSDC","source_url":"https://tnsdc.in","apply_url":"https://tnsdc.in"},
  {"title":"PM Mudra Yojana (Shishu)","title_ta":"PM முத்ரா கடன் திட்டம்","category":"job","subcategory":"micro_credit","description":"Collateral-free loans up to ₹50,000 for micro-entrepreneurs through banks and MFIs.","benefits":"Loan up to ₹50,000","amount":50000,"eligibility":{"min_age":18},"documents_required":["Aadhaar","PAN","Business Proof","Bank Statement"],"locations":[],"is_pan_india":True,"trust_score":0.96,"source":"MUDRA/RBI","source_url":"https://www.mudra.org.in","apply_url":"https://www.mudra.org.in"},
  {"title":"Startup India Seed Fund","title_ta":"ஸ்டார்ட்அப் இந்தியா விதை நிதி","category":"job","subcategory":"startup","description":"₹20–50 lakh grant for validated startups with prototype/MVP from incubators.","benefits":"Up to ₹50 lakh","amount":5000000,"eligibility":{"min_age":18,"max_age":45},"documents_required":["DPIIT Certificate","Business Plan","PAN","Aadhaar","Audited Accounts"],"locations":[],"is_pan_india":True,"trust_score":0.93,"source":"DPIIT","source_url":"https://www.startupindia.gov.in","apply_url":"https://seedfund.startupindia.gov.in"},
  # ── More Health/NGO ────────────────────────────────────────
  {"title":"National Programme for Control of Blindness","title_ta":"கண் பார்வை இலவச சிகிச்சை","category":"health","subcategory":"vision","description":"Free cataract surgery, spectacles and eye check-up through government camps across TN.","benefits":"Free surgery + glasses","amount":0,"eligibility":{},"documents_required":["Aadhaar","Doctor Screening"],"locations":[],"is_pan_india":True,"trust_score":0.96,"source":"NHM","source_url":"https://nhm.gov.in","apply_url":"https://nhm.tn.gov.in"},
  {"title":"NTEP – TB Free India Programme","title_ta":"இலவச TB சிகிச்சை","category":"health","subcategory":"tb","description":"Free diagnosis, treatment, nutrition support (₹500/month Nikshay Poshan) for TB patients.","benefits":"Free medicines + ₹500/month nutrition","amount":6000,"eligibility":{},"documents_required":["Doctor Prescription","Aadhaar","Bank Passbook"],"locations":[],"is_pan_india":True,"trust_score":0.99,"source":"MoHFW/NTEP","source_url":"https://tbcindia.gov.in","apply_url":"https://tbcindia.gov.in"},
  {"title":"National AIDS Control Programme","title_ta":"இலவச HIV/AIDS சிகிச்சை","category":"health","subcategory":"hiv","description":"Free ART treatment, CD4 testing and counselling for PLHIV at government ART centres.","benefits":"Free medicines + diagnostics","amount":0,"eligibility":{},"documents_required":["HIV Test Result","Aadhaar (optional)"],"locations":[],"is_pan_india":True,"trust_score":0.99,"source":"NACO","source_url":"https://naco.gov.in","apply_url":"https://naco.gov.in"},
  {"title":"Old Age Home – Government TN","title_ta":"அரசு முதியோர் இல்லம்","category":"ngo","subcategory":"elderly","description":"Free residential care, meals and healthcare for destitute senior citizens aged 60+ with no family support.","benefits":"Free shelter + food + healthcare","amount":0,"eligibility":{"min_age":60,"max_income":0},"documents_required":["Age Certificate","Aadhaar","Self-Declaration (No Family)"],"locations":["Chennai","Coimbatore","Madurai","Salem","Tiruchirappalli","Vellore"],"is_pan_india":False,"trust_score":0.92,"source":"TN Social Defence","source_url":"https://www.tn.gov.in","apply_url":"https://www.tn.gov.in"},
  {"title":"Sukanya Samriddhi Yojana","title_ta":"சுகன்யா சம்ரிட்தி திட்டம்","category":"ngo","subcategory":"girl_savings","description":"Tax-free savings scheme for girl child – deposit ₹250–1.5 lakh/year at 8.2% interest.","benefits":"8.2% interest + tax exemption","amount":0,"eligibility":{"gender":["F"],"max_age":10},"documents_required":["Birth Certificate","Parent Aadhaar","PAN","Photo"],"locations":[],"is_pan_india":True,"trust_score":0.99,"source":"Ministry of Finance","source_url":"https://www.india.gov.in","apply_url":"https://indiapostpayments.gov.in"},
  {"title":"Beti Bachao Beti Padhao","title_ta":"பேட்டி பசாவோ பேட்டி படாவோ","category":"ngo","subcategory":"girl_child","description":"Financial incentives and awareness programme for birth, education and welfare of girl child.","benefits":"Various district-level benefits","amount":0,"eligibility":{"gender":["F"],"max_age":18},"documents_required":["Birth Certificate","Aadhaar (parent)"],"locations":[],"is_pan_india":True,"trust_score":0.95,"source":"WCD Ministry","source_url":"https://wcd.nic.in","apply_url":"https://wcd.nic.in"},
  {"title":"Transgender Welfare Scheme TN","title_ta":"திருநங்கை நலத் திட்டம்","category":"ngo","subcategory":"transgender","description":"Monthly pension, free SRS surgery, counselling and skill training for transgender persons in TN.","benefits":"₹1,000/month pension + free surgery","amount":12000,"eligibility":{},"documents_required":["Transgender ID Certificate","Aadhaar","Bank Passbook"],"locations":[],"is_pan_india":False,"trust_score":0.93,"source":"TN Social Welfare","source_url":"https://www.tn.gov.in","apply_url":"https://www.tn.gov.in"},
  {"title":"Anganwadi Services (ICDS)","title_ta":"அங்கன்வாடி சேவைகள்","category":"health","subcategory":"child_nutrition","description":"Free supplementary nutrition, immunisation, preschool and health check-up for children 0-6 and pregnant/lactating mothers.","benefits":"Free nutrition + immunisation","amount":0,"eligibility":{"max_age":6},"documents_required":["Birth Certificate","Aadhaar (Mother)"],"locations":[],"is_pan_india":True,"trust_score":0.99,"source":"WCD/ICDS","source_url":"https://icds-wcd.nic.in","apply_url":"https://icds-wcd.nic.in"},
  {"title":"KALAIGNAR Magalir Urimai Thogai","title_ta":"கலைஞர் மகளிர் உரிமை தொகை","category":"ngo","subcategory":"women_dbt","description":"₹1,000/month direct cash transfer to women heads of eligible families in TN.","benefits":"₹1,000/month","amount":12000,"eligibility":{"gender":["F"],"max_income":250000},"documents_required":["Ration Card","Aadhaar","Bank Passbook"],"locations":[],"is_pan_india":False,"trust_score":0.99,"source":"TN Govt","source_url":"https://www.tn.gov.in","apply_url":"https://www.tn.gov.in"},
]


async def seed():
    engine = create_async_engine(settings.DATABASE_URL, echo=False)
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    Session = async_sessionmaker(engine, expire_on_commit=False)
    async with Session() as db:
        # Create admin user
        from sqlalchemy import select
        existing_admin = (await db.execute(select(User).where(User.email == settings.ADMIN_EMAIL))).scalar_one_or_none()
        if not existing_admin:
            admin = User(
                email=settings.ADMIN_EMAIL,
                hashed_password=hash_password(settings.ADMIN_PASSWORD),
                name="NaviAid Admin",
                role="admin",
            )
            db.add(admin)
            print(f"✓ Admin user created: {settings.ADMIN_EMAIL}")

        # Seed opportunities
        from sqlalchemy import select, func as sqlfunc
        existing_count = (await db.execute(select(sqlfunc.count()).select_from(Opportunity))).scalar()
        if existing_count and existing_count > 0:
            print(f"✓ {existing_count} opportunities already seeded. Skipping.")
        else:
            print("Generating embeddings for 100 opportunities...")
            texts = [build_opportunity_text(o) for o in OPPORTUNITIES]
            # Batch encode
            from app.ml.embed import encode_texts
            embeddings = encode_texts(texts)
            for i, opp_data in enumerate(OPPORTUNITIES):
                opp = Opportunity(
                    title=opp_data["title"],
                    title_ta=opp_data.get("title_ta"),
                    description=opp_data["description"],
                    category=opp_data["category"],
                    subcategory=opp_data.get("subcategory"),
                    source=opp_data.get("source"),
                    source_url=opp_data.get("source_url"),
                    apply_url=opp_data.get("apply_url"),
                    eligibility=opp_data.get("eligibility", {}),
                    documents_required=opp_data.get("documents_required", []),
                    benefits=opp_data.get("benefits"),
                    amount=opp_data.get("amount"),
                    locations=opp_data.get("locations", []),
                    is_pan_india=opp_data.get("is_pan_india", False),
                    trust_score=opp_data.get("trust_score", 0.85),
                    is_active=True,
                    embedding=str(embeddings[i]),  # store as string for SQLite
                )
                db.add(opp)
            print(f"✓ {len(OPPORTUNITIES)} opportunities seeded.")
        await db.commit()
    await engine.dispose()
    print("✓ Seed complete!")


if __name__ == "__main__":
    asyncio.run(seed())
